// SQLite database URL. Root uses /var/lib/ravelin/, non-root uses ~/.ravelin/.
pub const DB_URL: &str = "sqlite:///var/lib/ravelin/ravelin.db?mode=rwc";

// Max log lines shown in the LIVE FEED panel.
pub const LOG_CAP: usize = 200;
// Max raw log lines stored per IP for the INSPECT view.
pub const HISTORY_CAP: usize = 32;
// Max distinct IPs kept in history to bound memory.
pub const IP_HISTORY_KEY_CAP: usize = 512;
// Dedup window: recent event hashes to prevent double-counting.
pub const RECENT_EVENT_CAP: usize = 20_000;
// Max suspects displayed in the SUSPECTS panel.
pub const SUSPECT_CAP: usize = 1_000;

// Score at which an IP gets auto-blocked (after MIN_AUTO_BLOCK_EVENTS).
pub const AUTO_BLOCK_SCORE_THRESHOLD: u32 = 100;
// Minimum events from one IP before auto-block eligibility.
pub const MIN_AUTO_BLOCK_EVENTS: u32 = 5;

// Score per known-vulnerable path hit (.env, .git/config, phpinfo, etc.).
pub const SCANNER_PATH_SCORE: u32 = 50;
// Unique scanner paths before immediate auto-block (high enough to avoid Cloudflare/Telegram false positives).
pub const SCANNER_AUTO_BLOCK_THRESHOLD: usize = 15;
// Max IPs tracked for path scanner detection.
pub const SCANNER_IP_CAP: usize = 512;

// Points added per SSH auth failure.
pub const SSH_FAILURE_SCORE: u32 = 10;
// Points added per Suricata IDS alert.
pub const IDS_ALERT_SCORE: u32 = 25;
// Points added per HTTP 4xx client error.
pub const HTTP_CLIENT_ERROR_SCORE: u32 = 2;
// Points added per HTTP 5xx server error.
pub const HTTP_SERVER_ERROR_SCORE: u32 = 1;
// Points added for an HTTP error burst pattern.
pub const HTTP_ERROR_BURST_SCORE: u32 = 18;
// Points added for an HTTP success burst (scanner fingerprint).
pub const HTTP_SUCCESS_BURST_SCORE: u32 = 8;

// Max chars for a suspect's reason string in the UI.
pub const MAX_REASON_LEN: usize = 180;

// Max chars for a single LIVE FEED log line.
pub const MAX_UI_LOG_LEN: usize = 512;
// Max chars for a raw history line in INSPECT view.
pub const MAX_HISTORY_LINE_LEN: usize = 1_024;
// Max bytes per log line read from disk (longer lines are skipped).
pub const MAX_LOG_LINE_BYTES: usize = 8_192;
// Max chars for the command input buffer.
pub const MAX_COMMAND_BUFFER_CHARS: usize = 256;

// Max distinct IPs tracked for HTTP behavior analysis.
pub const HTTP_BEHAVIOR_IP_CAP: usize = 1_024;
// Max HTTP events kept per IP for behavior scoring.
pub const HTTP_BEHAVIOR_EVENT_CAP: usize = 128;
// Sliding window (seconds) for HTTP behavior analysis.
pub const HTTP_BEHAVIOR_WINDOW_SECS: i64 = 60;
// Cooldown (seconds) between behavioral signals per IP.
pub const HTTP_BEHAVIOR_SIGNAL_COOLDOWN_SECS: i64 = 30;

// Sliding window (seconds) for detecting HTTP bursts.
pub const HTTP_BURST_WINDOW_SECS: i64 = 10;
// Min total HTTP requests in burst window to evaluate.
pub const HTTP_BURST_MIN_REQUESTS: usize = 30;
// Min errors in burst window to flag as suspicious.
pub const HTTP_ERROR_BURST_MIN_ERRORS: usize = 8;
// Min requests with zero successes to trigger immediate block.
pub const HTTP_NO_SUCCESS_FLOOD_MIN_REQUESTS: usize = 100;
// Score for a 100% failure flood (immediate block).
pub const HTTP_NO_SUCCESS_FLOOD_SCORE: u32 = 125;
// Min requests in a success-only burst to flag as scanner.
pub const HTTP_SUCCESS_BURST_MIN_REQUESTS: usize = 40;

// Min total requests to evaluate predictable cadence.
pub const HTTP_REGULAR_MIN_REQUESTS: usize = 12;
// Min avg gap (ms) between requests to consider cadence regular.
pub const HTTP_REGULAR_MIN_AVG_GAP_MS: i64 = 250;
// Max avg gap (ms) — above this is too slow to be automated.
pub const HTTP_REGULAR_MAX_AVG_GAP_MS: i64 = 1_500;
// Max jitter (ms) — below this means machine-like timing.
pub const HTTP_REGULAR_MAX_JITTER_MS: i64 = 250;

// TUI event loop poll interval (ms). Lower = more responsive, higher CPU.
pub const EVENT_POLL_INTERVAL_MS: u64 = 100;
// How often (seconds) to poll Suricata eve.json for new lines.
pub const SURICATA_POLL_SECS: u64 = 2;
// Max lines to read from Suricata per poll cycle.
pub const SURICATA_MAX_LINES_PER_POLL: usize = 1_000;
// How often (seconds) to poll syslog for new entries.
pub const SYSLOG_POLL_SECS: u64 = 5;

// How often (seconds) to run the Suricata log cleanup.
pub const SURICATA_CLEANUP_SECS: u64 = 3_600;
// Retention: non-block logs older than this (hours) are purged from eve.json.
pub const EVE_RETENTION_NON_BLOCK_HOURS: i64 = 48;
// Retention: block-causing logs older than this (hours) are purged from eve.json.
pub const EVE_RETENTION_BLOCK_HOURS: i64 = 168;

// Path to Suricata's JSON event log.
pub const SURICATA_EVE_PATH: &str = "/var/log/suricata/eve.json";

// ipset name used by iptables DROP rules.
pub const IPSET_NAME: &str = "sentinel_block";
// Temp path prefix for the self-check installer script.
pub const SETUP_PATH_PREFIX: &str = "/tmp/ravelin_setup_";
// Reason string stored when user manually blocks an IP.
pub const MANUAL_BLOCK_REASON: &str = "Manual Block";
// Env var to list trusted IPs (comma-separated) that should never be blocked.
pub const TRUSTED_IPS_ENV: &str = "RAVELIN_TRUSTED_IPS";
// systemd unit name for the Ravelin daemon.
pub const BACKBONE_SERVICE_NAME: &str = "ravelin.service";

// Known paths probed by automated vulnerability scanners (nikto, nuclei, dirb,
// dirbuster, ffuf, gobuster, wfuzz, sqlmap, wpscan, cms scanners, etc.).
// Used by the scanner-path detector to flag IPs hitting these paths.
// Deduplicated across all major scanner default wordlists and template sets.
pub const SCANNER_PATTERNS: &[&str] = &[
    // ── Environment & Config Files ──────────
    ".env",
    ".env.local",
    ".env.dev",
    ".env.development",
    ".env.staging",
    ".env.production",
    ".env.backup",
    ".env.old",
    ".env.example",
    ".env.save",
    ".env.swp",
    ".env.bak",
    ".env~",
    ".env.json",
    ".env.js",
    ".env.dist",
    ".env.test",
    ".env.bakup",
    ".env.testing",
    ".env.local.php",
    ".env.docker",
    "config.php",
    "config.php.bak",
    "config.php.old",
    "config.php~",
    "config.inc.php",
    "config.inc.php.bak",
    "config.json",
    "config.yml",
    "config.yaml",
    "config.xml",
    "config.ini",
    "config.txt",
    "configuration.php",
    "configuration.php.bak",
    "configuration.php.old",
    "configuration.yml",
    "settings.py",
    "settings.json",
    "settings.yml",
    "settings.yaml",
    "settings.local.php",
    "settings.pyc",
    "local_settings.py",
    "local_settings.py.bak",
    "application.properties",
    "application.yml",
    "application.yaml",
    "application-local.properties",
    "application-dev.properties",
    "application-prod.properties",
    "application-test.properties",
    "wp-config.php",
    "wp-config.php.bak",
    "wp-config.php.old",
    "wp-config.php.save",
    "wp-config.php.swp",
    "wp-config.php~",
    "wp-config.php.dist",
    "wp-config.inc",
    "wp-config.php.txt",
    "wp-config-sample.php",
    ".htaccess",
    ".htpasswd",
    ".htaccess.bak",
    "web.config",
    "web.config.bak",
    "crossdomain.xml",
    "clientaccesspolicy.xml",
    "httpd.conf",
    "nginx.conf",
    "server.xml",
    "php.ini",
    "php.ini.bak",
    "php.ini.old",
    "php.ini~",
    "credentials",
    "credentials.json",
    "credentials.txt",
    "secret.json",
    "secret.key",
    "secrets.yml",
    "secrets.yaml",
    "key.txt",
    "key.pem",
    "private.key",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "htpasswd",
    "htpasswd.bak",
    "passwd",
    // ── Debug & Diagnostic Endpoints ────────────────────────────────────
    "debug.php",
    "debug.html",
    "debug.json",
    "debug.log",
    "debug.txt",
    "debug.log.1",
    "debug/",
    "debug/default/view",
    "debug/default/toolbar",
    "debug/default/collector",
    "__debug__/",
    "__debug__",
    "__debug__/sql_time/",
    "__debug__/render_time/",
    "__debug__/memory_time/",
    "__debug__/view_list/",
    "__debug__/sqltime/",
    "__debug__/settings/",
    "trace.axd",
    "trace/",
    "elmah.axd",
    "phpinfo.php",
    "php_info.php",
    "phpinfo.php.bak",
    "php-test.php",
    "test.php",
    "test.php?cmd=phpinfo",
    "test/",
    "info.php",
    "info.html",
    "p.php",
    "pi.php",
    "i.php",
    "status",
    "status.php",
    "status/",
    "status?auto",
    "server-status",
    "server-status/",
    "server-status?auto",
    "server-status?refresh=5",
    "server-info",
    "server-info/",
    "server-info?auto",
    "mod_status",
    "mod_status?auto",
    "mod_security_status/",
    "nginx_status",
    "nginx_status?auto",
    "health",
    "health/",
    "healthz",
    "healthcheck",
    "health-check/",
    "ping/",
    "ping",
    "ready",
    "ready/",
    "readiness",
    "liveness",
    "metrics/",
    "metrics",
    "monitor/",
    "monitoring/",
    "monitor/?all",
    "monitor/connected",
    "stats/",
    "statistics/",
    "info/",
    "version",
    "version/",
    "version.txt",
    "version.php",
    "RELEASE",
    "CHANGELOG",
    "CHANGELOG.txt",
    "CHANGELOG.md",
    "CHANGES",
    "CHANGES.txt",
    "NEWS",
    "TODO",
    "LICENSE",
    "LICENSE.txt",
    "LICENSE.md",
    "COPYING",
    "AUTHORS",
    "CONTRIBUTORS",
    "errors",
    "error.log",
    "error_log",
    "error.html",
    "php_errors.log",
    "server.log",
    "application.log",
    "access.log",
    "access_log",
    "access.log.1",
    "access_log.1",
    "system.log",
    "system.log.1",
    "laravel.log",
    "development.log",
    "php-security.php",
    "php-security",
    // ── Backup & Dump Files ─────────────────
    "backup",
    "backup.sql",
    "backup.sql.gz",
    "backup.zip",
    "backup.tar.gz",
    "backup.tgz",
    "backup.bak",
    "backup.old",
    "backup.html",
    "backup.php",
    "backup_",
    "backups",
    "backup.sql.bak",
    "backup.tar",
    "backup.rar",
    "backup.7z",
    "bak.zip",
    "old.zip",
    "new.zip",
    "temp.zip",
    "tmp.zip",
    "test.zip",
    "dev.zip",
    "prod.zip",
    "staging.zip",
    "dump.sql",
    "dump.sql.gz",
    "dump.rdb",
    "dump.rdb.gz",
    "dump.tar.gz",
    "dump.zip",
    "dump.json",
    "database.sql",
    "database.sql.gz",
    "database.sql.bak",
    "database.sql.old",
    "database.sqlite3",
    "db.sql",
    "db.sql.gz",
    "db.sqlite",
    "db.sqlite3",
    "db.sqlite3.bak",
    "db.sqlite3.old",
    "db.sqlite3~",
    "db.json",
    "db_backup.sql",
    "db-dump.sql",
    "db_backup.zip",
    "db_dump.zip",
    "mysql.sql",
    "data.sql",
    "data.sql.gz",
    "export.sql",
    "export.sql.gz",
    "import.sql",
    "www.sql",
    "www.zip",
    "www.tar.gz",
    "www.bak",
    "www-old.zip",
    "site.sql",
    "site.zip",
    "site.tar.gz",
    "html.zip",
    "html.tar.gz",
    "web.zip",
    "web.tar.gz",
    "public.zip",
    "src.zip",
    "source.zip",
    "code.zip",
    "archive.zip",
    "archive.tar.gz",
    "bak.sql",
    "bkp.sql",
    "sql.zip",
    "sql.tar.gz",
    ".sql",
    ".sql.gz",
    ".sql.bak",
    "dev.sql",
    "prod.sql",
    "staging.sql",
    ".zip",
    ".tar",
    ".tar.gz",
    ".tgz",
    ".rar",
    ".7z",
    ".bz2",
    ".bak",
    ".old",
    ".orig",
    ".save",
    ".swp",
    ".swo",
    ".tmp",
    ".temp",
    ".copy",
    ".backup",
    // ── Source Control Exposure ──────────────
    ".git/",
    ".git/HEAD",
    ".git/config",
    ".git/index",
    ".git/logs/",
    ".git/logs/HEAD",
    ".git/logs/refs/heads/master",
    ".git/refs/heads/master",
    ".gitignore",
    ".gitattributes",
    ".gitmodules",
    ".gitreview",
    ".gitkeep",
    ".svn/",
    ".svn/entries",
    ".svn/wc.db",
    ".svn/all-wcprops",
    ".svn/dir-prop-base",
    ".svnignore",
    ".hg/",
    ".hg/store/00manifest.i",
    ".hgignore",
    ".bzr/",
    "CVS/",
    "CVS/Entries",
    "CVS/Root",
    "CVS/Repository",
    // ── VCS & OS Artifact Files ─────────────
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    ".bash_history",
    ".bashrc",
    ".profile",
    ".ssh/",
    ".ssh/authorized_keys",
    ".ssh/id_rsa",
    ".ssh/id_dsa",
    ".ssh/id_ecdsa",
    ".ssh/id_ed25519",
    ".rhosts",
    ".forward",
    ".mysql_history",
    ".psql_history",
    ".python_history",
    ".viminfo",
    ".wget-hsts",
    ".lesshst",
    ".pki/",
    ".docker/",
    ".dockerenv",
    ".dockerignore",
    // ── Docker / Kubernetes / IaC ───────────
    "docker-compose.yml",
    "docker-compose.yaml",
    "docker-compose.override.yml",
    "docker-compose.dev.yml",
    "docker-compose.prod.yml",
    "docker-compose.yml.bak",
    "Dockerfile",
    "Dockerfile.dev",
    "Dockerfile.prod",
    "Vagrantfile",
    "Procfile",
    // ── Cloud & Metadata ────────────────────
    "metadata/",
    "metadata/latest/",
    "metadata/latest/meta-data/",
    "metadata/latest/meta-data/instance-id",
    "metadata/latest/meta-data/hostname",
    "metadata/latest/meta-data/local-ipv4",
    "metadata/latest/meta-data/public-ipv4",
    "metadata/latest/meta-data/iam/",
    "metadata/latest/meta-data/iam/security-credentials/",
    "metadata/latest/user-data/",
    ".aws/",
    ".aws/credentials",
    ".aws/config",
    ".aws/sts/",
    "latest/",
    "latest/meta-data/",
    "latest/meta-data/iam/",
    "latest/meta-data/iam/security-credentials/",
    "latest/user-data",
    "169.254.169.254/",
    // ── Admin Panels & Login Pages ──────────
    "admin",
    "admin/",
    "admin.php",
    "admin.html",
    "admin.cgi",
    "admin/index.php",
    "admin/login.php",
    "admin/login",
    "admincp/",
    "admincp/index.php",
    "administrator/",
    "administrator/index.php",
    "administrator/login.php",
    "administrator/manifests/",
    "admin-panel/",
    "admin-console/",
    "admin-interface/",
    "admin_area/",
    "adminlogin",
    "adminlogon",
    "adminpanel",
    "admin1/",
    "admin2/",
    "admin3/",
    "cpanel",
    "cpanel/",
    "cpanel.html",
    "whm/",
    "webmin/",
    "plesk/",
    "phpmyadmin/",
    "phpmyadmin/index.php",
    "phpmyadmin/phpinfo.php",
    "phpmyadmin/index.php?lang=en",
    "pma/",
    "pma/index.php?lang=en",
    "myadmin/",
    "myadmin/index.php?lang=en",
    "adminer/",
    "adminer.php",
    "adminer.php?sql=",
    "adminer.php?server=1",
    "dbadmin/",
    "dbadmin.php",
    "mysql/",
    "mysqlmanager/",
    "sqlmanager/",
    "sql-admin/",
    "sqladmin/",
    "sqlphpmyadmin/",
    "webadmin/",
    "server-admin/",
    "panel/",
    "manage/",
    "dashboard/",
    "console/",
    "console/css/",
    "console/js/",
    "backend/",
    "backoffice/",
    "supervisor/",
    "superadmin/",
    "super-admin/",
    "system-admin/",
    "sysadmin/",
    "login",
    "login.php",
    "login.html",
    "login.asp",
    "login.jsp",
    "login.aspx",
    "signin",
    "signin.php",
    "signin.html",
    "wp-login.php",
    "wp-login.php?action=register",
    "wp-login.php?action=lostpassword",
    "wp-admin/",
    "wp-admin/index.php",
    "wp-admin/admin-ajax.php",
    "wp-admin/install.php",
    "wp-admin/setup-config.php",
    "wp-admin/upgrade.php",
    "wp-admin/export.php",
    "wp-admin/import.php",
    "wp-signup.php",
    "install.php",
    "install/index.php",
    "install/install.php",
    "setup.php",
    "setup/",
    "setup/install.php",
    "setup/install/",
    "setup/index.php",
    "upgrade.php",
    "upgrade/",
    // ── Sensitive Standard Files ─────────────
    "robots.txt",
    "robots.txt.bak",
    "sitemap.xml",
    "sitemap.xml.gz",
    "sitemap_index.xml",
    "security.txt",
    "security.txt.bak",
    ".well-known/security.txt",
    "humans.txt",
    "favicon.ico",
    "favicon.png",
    ".well-known/",
    ".well-known/apple-app-site-association",
    ".well-known/openid-configuration",
    ".well-known/change-password",
    ".well-known/host-meta",
    ".well-known/jwks.json",
    ".well-known/assetlinks.json",
    "manifest.json",
    "browserconfig.xml",
    "README",
    "README.md",
    "README.txt",
    "README.html",
    "readme.htm",
    "INSTALL",
    "INSTALL.txt",
    "INSTALL.md",
    // ── Build / Dependency Files (may leak secrets / config) ─────────────
    "webpack.config.js",
    ".babelrc",
    ".eslintrc",
    ".prettierrc",
    "tsconfig.json",
    "composer.json",
    "composer.lock",
    "package.json",
    "package-lock.json",
    "yarn.lock",
    "Gemfile",
    "Gemfile.lock",
    "Pipfile",
    "Pipfile.lock",
    "requirements.txt",
    "requirements.txt.bak",
    "requirements-dev.txt",
    "go.mod",
    "go.sum",
    "Cargo.toml",
    "Cargo.lock",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "build.sbt",
    "mix.exs",
    "Makefile",
    "Makefile.bak",
    "Rakefile",
    "Gruntfile.js",
    "Gulpfile.js",
    ".editorconfig",
    // ── API Documentation & GraphQL ─────────
    "swagger",
    "swagger/",
    "swagger-ui/",
    "swagger-ui.html",
    "swagger-ui/index.html",
    "swagger.json",
    "swagger.yaml",
    "swagger-docs",
    "api-docs/",
    "api-docs",
    "api/swagger",
    "api/swagger-ui",
    "api/docs",
    "api-doc/",
    "api/v1/docs",
    "api/v2/docs",
    "api/v3/docs",
    "docs/",
    "docs/api",
    "documentation/",
    "graphql",
    "graphql/",
    "graphql/console",
    "graphiql",
    "graphiql/",
    "_graphiql",
    "playground",
    "playground/",
    "altair",
    "altair/",
    "v1/api-docs",
    "v2/api-docs",
    "v3/api-docs",
    "openapi.json",
    "openapi.yaml",
    "openapi.yml",
    "api.json",
    "api.yaml",
    "redoc/",
    "redoc",
    "apidoc/",
    // ── WordPress Specific ──────────────────
    "wp-content/",
    "wp-content/debug.log",
    "wp-content/uploads/",
    "wp-content/plugins/",
    "wp-content/themes/",
    "wp-content/advanced-cache.php",
    "wp-content/wp-cache-config.php",
    "wp-content/object-cache.php",
    "wp-content/db.php",
    "wp-content/mu-plugins/",
    "wp-content/mu-plugins/install.php",
    "wp-includes/",
    "wp-includes/js/tinymce/",
    "wp-cron.php",
    "xmlrpc.php",
    "xmlrpc.php?rsd",
    "xmlrpc.php?wbj",
    "xmlrpc.php?backslash",
    "wp-json/",
    "wp-json/wp/v2/users",
    "wp-json/wp/v2/posts",
    "wp-json/wp/v2/pages",
    "wp-json/wp/v2/media",
    "wp-json/wp/v2/settings",
    "wp-trackback.php",
    "wp-rss.php",
    "wp-rss2.php",
    "wp-rdf.php",
    "wp-atom.php",
    "wp-feed.php",
    "wp-commentsrss2.php",
    "wp-links-opml.php",
    "wp-mail.php",
    "wp-app.php",
    "wp-settings.php",
    "wp-load.php",
    "wp-blog-header.php",
    "wp-activate.php",
    "wp-comments-post.php",
    // ── Laravel Specific ────────────────────
    "telescope",
    "telescope/",
    "telescope/requests",
    "telescope/exceptions",
    "telescope/logs",
    "telescope/schedule",
    "horizon/",
    "horizon",
    "ignition/",
    "ignition",
    "_ignition/health-check",
    "_ignition/execute-solution",
    "_ignition/share",
    "storage/logs/laravel.log",
    "storage/logs/",
    "storage/",
    "storage/app/",
    "storage/app/public/",
    "storage/framework/",
    "storage/framework/sessions/",
    "storage/framework/views/",
    "public/storage/",
    "config/",
    "config/app.php",
    "config/database.php",
    "config/app.php.bak",
    "config/database.php.bak",
    "artisan",
    "artisan.bak",
    "vendor/",
    "vendor/phpunit/",
    // ── Django Specific ─────────────────────
    "admin/login/",
    "admin/password_reset/",
    "static/admin/",
    "static/",
    "api/v1/",
    "api/v2/",
    "api/v3/",
    "api/auth/",
    "api/users/",
    "api/token/",
    "api/login/",
    "api/schema/",
    "api/schema/swagger/",
    "api/schema/redoc/",
    "api/docs/",
    "django-admin/",
    "manage.py",
    "urls.py",
    "wsgi.py",
    "celery.py",
    "fixture/",
    "fixtures/",
    // ── Spring Boot / Java Actuator ─────────
    "actuator",
    "actuator/",
    "actuator/health",
    "actuator/healthz",
    "actuator/info",
    "actuator/env",
    "actuator/env/",
    "actuator/beans",
    "actuator/configprops",
    "actuator/configprops/",
    "actuator/mappings",
    "actuator/mappings/",
    "actuator/trace",
    "actuator/trace/",
    "actuator/httptrace",
    "actuator/httptrace/",
    "actuator/dump",
    "actuator/dump/",
    "actuator/threaddump",
    "actuator/threaddump/",
    "actuator/metrics",
    "actuator/metrics/",
    "actuator/heapdump",
    "actuator/heapdump/",
    "actuator/logfile",
    "actuator/logfile/",
    "actuator/loggers",
    "actuator/loggers/",
    "actuator/conditions",
    "actuator/scheduledtasks",
    "actuator/sessions",
    "actuator/shutdown",
    "actuator/shutdown/",
    "actuator/jolokia",
    "actuator/jolokia/",
    "actuator/auditevents",
    "actuator/autoconfig",
    "actuator/caches",
    "actuator/flyway",
    "actuator/liquibase",
    "actuator/integrationgraph",
    "actuator/restart",
    "actuator/pause",
    "actuator/resume",
    "actuator/refresh",
    // ── Java / Servlet Containers (general) ─────────────────────────────
    "env",
    "env/",
    "mappings",
    "mappings/",
    "beans",
    "beans/",
    "configprops",
    "configprops/",
    "heapdump",
    "heapdump/",
    "dump",
    "dump/",
    "jolokia",
    "jolokia/",
    "jolokia/list",
    "WEB-INF/",
    "WEB-INF/web.xml",
    "WEB-INF/web.xml.bak",
    "WEB-INF/classes/",
    "WEB-INF/classes/config.properties",
    "WEB-INF/classes/application.properties",
    "WEB-INF/classes/application.yml",
    "WEB-INF/lib/",
    "META-INF/",
    "META-INF/MANIFEST.MF",
    "META-INF/maven/",
    "META-INF/spring/",
    "META-INF/spring.factories",
    "META-INF/resources/",
    "ws_utc/",
    "ws_utc/config",
    "war/",
    "war/WEB-INF/web.xml",
    // ── Tomcat Manager ──────────────────────
    "manager/",
    "manager/html",
    "manager/status",
    "manager/text",
    "manager/list",
    "manager/jmxproxy",
    "manager/status/all",
    "host-manager/",
    "host-manager/html",
    "host-manager/status",
    "host-manager/text",
    "host-manager/list",
    "host-manager/start",
    "host-manager/stop",
    "host-manager/deploy",
    "host-manager/undeploy",
    "examples/",
    "examples/jsp/",
    "examples/jsp/date.jsp",
    "examples/servlet/",
    "examples/servlet/HelloWorld",
    "examples/servlet/RequestParameterExample",
    "servlet/",
    "servlet/SnoopServlet",
    // ── WebLogic / JBoss / ColdFusion ───────────────────────────────────
    "wls-wsat/CoordinatorPortType",
    "wls-wsat/CoordinatorPortType11",
    "wls-wsat/RegistrationPortTypeRPC",
    "wls-wsat/RegistrationPortTypeRPC11",
    "wls-wsat/ParticipantPortType",
    "wls-wsat/ParticipantPortType11",
    "wls-wsat/RegistrationRequesterPortType",
    "wls-wsat/RegistrationRequesterPortType11",
    "uddiexplorer/",
    "uddiexplorer/SearchPublicRegistries.jsp",
    "invoker/JMXInvokerServlet",
    "invoker/EJBInvokerServlet",
    "jmx-console/",
    "jmx-console/HtmlAdaptor",
    "web-console/",
    "web-console/ServerInfo.jsp",
    "CFIDE/",
    "CFIDE/administrator/",
    "CFIDE/administrator/index.cfm",
    "CFIDE/probe.cfm",
    "CFIDE/scripts/",
    "CFIDE/scripts/ajax/package/cfajax.js",
    "CFIDE/scripts/ajax/package/cfquery.js",
    "CFIDE/debug/",
    "cfdocs/",
    "cfdocs/expeval/ExprCalc.cfm",
    "cfdocs/expeval/OpenFile.cfm",
    "axis/",
    "axis2/",
    "axis2-admin/",
    "axis2-admin/login",
    "axis-services/",
    "axis/happyaxis.jsp",
    // ── Jenkins / CI-CD ─────────────────────
    "jenkins/",
    "jenkins/login",
    "jenkins/script",
    "jenkins/manage",
    "jenkins/securityRealm",
    "jenkins/scriptConsole",
    "jenkins/api/",
    "jenkins/api/json",
    "jenkins/api/python",
    "jenkins/api/python?tree=name,url",
    "jenkins/computer/",
    "jenkins/job/",
    "jenkins/view/",
    "jenkins/manage/configureTools",
    "jenkins/manage/configureSystem",
    "jenkins/manage/configureClouds",
    "jenkins/manage/nodes",
    "jenkins/manage/plugins",
    "jenkins/manage/users",
    "jenkins/manage/credentials",
    "jenkins/manage/scriptApproval",
    "Jenkinsfile",
    "Jenkinsfile.bak",
    ".github/",
    ".github/workflows/",
    ".github/workflows/ci.yml",
    ".github/workflows/deploy.yml",
    ".gitlab-ci.yml",
    "bitbucket-pipelines.yml",
    "bitbucket-pipelines.yml.bak",
    ".circleci/",
    ".circleci/config.yml",
    ".travis.yml",
    "azure-pipelines.yml",
    "cloudbuild.yaml",
    "cloudbuild.yml",
    "buildspec.yml",
    ".drone.yml",
    "appveyor.yml",
    ".appveyor.yml",
    "wercker.yml",
    "buildkite.yml",
    // ── IIS / FrontPage / ASP.NET ───────────
    "iisstart.htm",
    "iis-85.png",
    "aspnet_client/",
    "aspnet_client/system_web/",
    "aspnet_client/system_web/4_0_30319/",
    "_vti_bin/",
    "_vti_bin/shtml.dll",
    "_vti_bin/_vti_inf.html",
    "_vti_bin/_vti_adm/admin.dll",
    "_vti_bin/_vti_aut/author.dll",
    "_vti_inf.html",
    "_vti_cnf/",
    "_vti_pvt/",
    "_vti_log/",
    "_vti_txt/",
    "_vti_map/",
    "W3SVC/",
    "W3SVC1/",
    "W3SVC2/",
    "ScriptResource.axd",
    "WebResource.axd",
    "ErrorPage.aspx",
    // ── CGI Probes ──────────────────────────
    "cgi-bin/",
    "cgi-bin/test-cgi",
    "cgi-bin/printenv",
    "cgi-bin/env.cgi",
    "cgi-bin/status",
    "cgi-bin/Count.cgi",
    "cgi-bin/php",
    "cgi-bin/perl",
    "cgi-bin/python",
    "cgi-bin/shell",
    "cgi-bin/test",
    "cgi-bin/test.cgi",
    "cgi-sys/",
    "cgi-bin-sys/",
    "cgi-local/",
    "cgi-exe/",
    "cgi-perl/",
    "cgi-pub/",
    "cgi-shl/",
    "cgi-web/",
    "fcgi-bin/",
    "fcgi-bin/php",
    "fcgi-bin/php5",
    "nph-test.cgi",
    "test.cgi",
    "test.pl",
    "test.py",
    // ── Perl / Server Status ────────────────
    "perl-status",
    "perl-info",
    "server-perl/",
    "server-perl-status",
    // ── Common Web Shells / Backdoor Indicators ─────────────────────────
    "shell.sh",
    "shell.php",
    "shell2.php",
    "cmd.php",
    "cmd.asp",
    "cmd.aspx",
    "command.php",
    "system.php",
    "exec.php",
    "c99.php",
    "c99shell.php",
    "r57.php",
    "r57shell.php",
    "b374k.php",
    "wso.php",
    "wso2.php",
    "wso2.8.5.php",
    "wso.php3",
    "wso2.8.5.php3",
    "webshell.php",
    "webshell3.php",
    "backdoor.php",
    "angel.php",
    "filesman.php",
    "FileManager.php",
    "FilesManager.php",
    "phpspy.php",
    "phpproxy.php",
    "phpinclude.php",
    "phpinvoker.php",
    "phpwget.php",
    "p0wny@shell.php",
    "poshon-shell.php",
    "weevely.php",
    "wephpshell.php",
    "rootsh.php",
    "sniper.php",
    "viper.php",
    "v007.php",
    "ncc.php",
    "ncc30.php",
    "mkt3ls.php",
    "udp.php",
    "udp350.php",
    "x86.php",
    "x99.php",
    "xxl.php",
    "zz.php",
    // ── Generic Probe Files ─────────────────
    "x.php",
    "xx.php",
    "xxxx.php",
    "r.php",
    "1.php",
    "12.php",
    "123.php",
    "a.php",
    "b.php",
    "test1.php",
    "test2.php",
    "test5.php",
    "hack.php",
    "hacked.php",
    "error404.php",
    // ── Upload Probes ───────────────────────
    "upload.php",
    "upload.html",
    "upload.asp",
    "upload.jsp",
    "upload.php3",
    "upload.php5",
    "upload.pl",
    "upload.py",
    "filemanager/",
    "file-upload.php",
    "fileupload.php",
    "file_upload.php",
    "upload_file.php",
    "uploads/",
    "upload/",
    // ── Logging & Data Exposure ─────────────
    "log/",
    "logs/",
    "logs/error.log",
    "logs/access.log",
    "log/error.log",
    "log/access.log",
    "temp/",
    "tmp/",
    "cache/",
    "data/",
    "database/",
    "databases/",
    "db/",
    "sql/",
    // ── Monitoring & Analytics (scanner targets) ────────────────────────
    "prometheus/",
    "prometheus/targets",
    "prometheus/config",
    "kibana/",
    "kibana/app/",
    "kibana/api/status",
    "kibana/app/discover",
    "grafana/",
    "nagios/",
    "nagios/cgi-bin/",
    "nagios/cgi-bin/tac.cgi",
    "zabbix/",
    "zabbix/api_jsonrpc.php",
    "cacti/",
    "munin/",
    "webalizer/",
    "awstats.pl",
    "awstats/",
    "matomo/",
    "piwik/",
    "analytics/",
    "elasticsearch/",
    "elasticsearch/_cluster/health",
    "elasticsearch/_cat/indices",
    "elasticsearch/_nodes",
    "elasticsearch/_search",
    "solr/admin/",
    "solr/admin/cores",
    "solr/admin/luke",
    "solr/admin/stats",
    // ── Webmail / Exchange / OWA ────────────
    "owa/",
    "owa",
    "owa/auth/logon.aspx",
    "ecp/",
    "exchange/",
    "exchange/LogonFrm.asp",
    "Autodiscover/",
    "Autodiscover/Autodiscover.xml",
    "autodiscover/autodiscover.json",
    "ews/",
    "ews/exchange.asmx",
    "ews/services.wsdl",
    "ews/exchange.wsdl",
    "mapi/",
    "mapi/emsmdb/",
    "oab/",
    "public/",
    "public/Web.config",
    "Sync/",
    "Sync/ContentMail",
    "mcx/",
    "mcx/Service",
    "nspi/",
    "availability/",
    // ── Remote Access / VPN ─────────────────
    "rpc/",
    "rpc/rpc2",
    "rpc/v2",
    "vnc/",
    "vnc.html",
    "rdp/",
    "rdpweb/",
    "tsweb/",
    "Remote/",
    "remote/login",
    "Remote/Desktop",
    "Remote/WebConnect",
    "vpn/",
    "vpn/index.html",
    // ── CMS: Joomla ─────────────────────────
    "joomla/",
    "joomla/administrator/",
    // ── CMS: Drupal ─────────────────────────
    "drupal/",
    "drupal/user/login",
    "drupal/admin/",
    "drupal/node/",
    "drupal/CHANGELOG.txt",
    "drupal/CHANGELOG",
    "drupal/core/CHANGELOG.txt",
    // ── CMS: Magento ────────────────────────
    "magento/",
    "magento/admin/",
    "magento/downloader/",
    "magento/app/etc/local.xml",
    "magento/var/export/",
    // ── CMS: PrestaShop ────────────────────
    "prestashop/",
    "prestashop/admin/",
    "prestashop/config/settings.inc.php",
    // ── CMS: Typo3 ─────────────────────────
    "typo3/",
    "typo3conf/",
    "typo3conf/localconf.php",
    "typo3conf/database.sql",
    // ── CMS: MediaWiki ──────────────────────
    "mediawiki/",
    "mediawiki/index.php",
    "mediawiki/LocalSettings.php",
    "mediawiki/config/",
    // ── CMS: Concrete5 ──────────────────────
    "concrete5/",
    "concrete5/index.php/login",
    // ── CMS: Contao ─────────────────────────
    "contao/",
    "contao/contao/",
    // ── CMS: SilverStripe ───────────────────
    "silverstripe/",
    "silverstripe/admin/",
    // ── CMS: Craft ──────────────────────────
    "craft/",
    "craft/admin/",
    // ── CMS: Umbraco ────────────────────────
    "umbraco/",
    "umbraco/login/",
    // ── CMS: Sitecore ───────────────────────
    "sitecore/",
    "sitecore/login/",
    // ── CMS: DotNetNuke ─────────────────────
    "dotnetnuke/",
    "dotnetnuke/Install/",
    // ── CMS: Shopware ───────────────────────
    "shopware/",
    // ── E-commerce & Payment ────────────────
    "cart/",
    "checkout/",
    "orders/",
    "shop/",
    "store/",
    "payment/",
    "billing/",
    "api/payment/",
    "api/checkout/",
    "invoice/",
    "receipt/",
    // ── Router / IoT Probe Paths ────────────
    "HNAP1/",
    "HNAP1",
    "tmUnblock.cgi",
    "apply.cgi",
    "boardDataWW.php",
    "hndUnblock.cgi",
    // ── CVE / Exploit Indicators ────────────
    "rce.jsp",
    "rce.php",
    "rce.py",
    "rce.sh",
    "cve-2021-44228",
    "cve-2023-",
    "cve-2024-",
    "log4shell",
    // ── Misc High-Value Paths ───────────────
    "icons/",
    "icons/small/",
    "icons/README",
    "manual/",
    "manual/index.html",
    "autoindex/",
    "auto_index/",
    "error.aspx",
    "400.html",
    "401.html",
    "403.html",
    "403.htm",
    "404.html",
    "404.htm",
    "404.aspx",
    "404.php",
    "500.html",
    "500.htm",
    "500.aspx",
    "500.php",
];

// Embedded bash script run by system_self_check to install deps and set up firewall.
pub const INSTALLER_SCRIPT: &str = r#"#!/bin/bash
set -euo pipefail

echo "[RAVELIN] Self-Check Initiated..."

if [ "$(id -u)" -ne 0 ]; then
  echo "[RAVELIN] Error: self-check must run as root." >&2
  exit 1
fi

if [ -f /etc/debian_version ]; then
  missing=()
  for pkg in suricata ipset jq iptables; do
    if ! dpkg -s "$pkg" >/dev/null 2>&1; then
      missing+=("$pkg")
    fi
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    echo "[RAVELIN] Installing Dependencies (apt)..."
    apt-get update -qq || echo "[RAVELIN] Warning: apt update reported repository warnings; using available package indexes." >&2
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${missing[@]}"
  fi
elif [ -f /etc/redhat-release ]; then
  missing=()
  for pkg in suricata ipset jq iptables; do
    if ! rpm -q "$pkg" >/dev/null 2>&1; then
      missing+=("$pkg")
    fi
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    echo "[RAVELIN] Installing Dependencies (yum)..."
    yum install -y epel-release || true
    yum install -y "${missing[@]}"
  fi
fi

echo "[RAVELIN] Configuring Firewall Defense..."
ipset create sentinel_block hash:ip timeout 0 -exist 2>/dev/null || true

ensure_drop_rule() {
  chain="$1"
  if ! iptables -L "$chain" -n >/dev/null 2>&1; then
    return
  fi

  while iptables -D "$chain" -m set --match-set sentinel_block src -j DROP 2>/dev/null; do
    true
  done

  iptables -I "$chain" 1 -m set --match-set sentinel_block src -j DROP
  echo "[RAVELIN] IPTables $chain Drop Rule Ready."
}

ensure_drop_rule INPUT
ensure_drop_rule DOCKER-USER

echo "[RAVELIN] Tuning Network Stack..."
sysctl -w net.core.netdev_max_backlog=500000 >/dev/null || true
sysctl -w net.core.rmem_max=134217728 >/dev/null || true

echo "[RAVELIN] Bounding Suricata log storage..."
cat >/etc/logrotate.d/ravelin-suricata <<'LOGROTATE'
/var/log/suricata/eve.json /var/log/suricata/fast.log /var/log/suricata/stats.log {
  size 64M
  rotate 4
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
}
LOGROTATE

echo "[RAVELIN] System Ready."
"#;
